### ISSUE TITLE
Provide a quick-start guide in the README

### ISSUE THREAD

**Issue by mirceanton** [supabase/storage-js#45]
# Improve documentation

## Link 

[README](https://github.com/supabase/storage-js/blob/main/README.md)

## Describe the problem

In other supabase components, such as [postgrest-js](https://github.com/supabase/postgrest-js/blob/master/README.md#quick-start), [realtime-js](https://github.com/supabase/realtime-js#usage) and [gotrue-js](https://github.com/supabase/gotrue-js#quick-start), there are short quick start sections in the readme to show you how you can get up and running without using the `supabase-js` package.

## Describe the improvement

Add a few code snippets that will document a quick start procedure.

**Comment by mikeanth-dev** [comment]
I noticed this because I have to use this module in my project now and I had to check the source code to see how I can create a new `SupabaseStorageClient`. Not that it is the end of the world, but it would be nice to have a quick guide in the readme like the other modules do.

I may take a look at it and provide some code samples and a PR this week.
